In [1]:
# Sección 1.5: numpy Module, modificación y ejemplos del libro
import numpy as np # importar el módulo para poder hacer uso de el

# desarrollar ejemplos de matrices de ceros y unos.
print('* Usando numpy se crea una matriz A de 3 filas x 3 columnas, de tipo int:'); print(' ')
A = np.zeros((3,3), int); print(A); print(' ')
print('* Usando numpy se crea una matriz B de 5 filas x 2 columnas, elemntos de tipo float:'); print(' ')
B = np.ones((5, 2), float); print(B); print(type(B)); print(' ') # buscar: ndarry type
print('* Usando numpy se crea un arreglo C que inicia en -10 y termina en 5-1, e incrementos de 1:'); print(' ')
C = np.arange(-5, 5, 1); print(C); print(' ')
print('* Los arrays son mutables, cambiaremos el elemento en la segunda fila y tercera columna de A por un 2000:'); print(' ')
A[1,2] = 2000; print(A); print(' ')
print('* Ahora convertimos la segunda fila en 2s:'); print(' ')
A[1,:] = 2; print(A); print(' ')
print('* Ejemplo de operación sobre todos los elementos de un array, elevarlos al cubo A:'); print(' ')
A = A**3; print(A); print(' ')
print('* Operaciones de Matrices')

# Estos ejemplos son tomados del apéndice A2 del libro NME (Kiusalaas, 2013):
# Example A4
#BA = np.array([[4,-2,1],[-2,4,-2],[1,-2,3]],int)
m_A = np.array([[1, 2, 3], [1, 2, 1], [0, 1, 2]])
m_v = np.array([1, 6, -2]); 
m_u = np.array([8, 0, -3]); 
print(m_A, m_v, m_u); print(' ')

# Determinantes
m_An = np.array([[5, -2], [-3, 4]])
m_bn =  np.array([1,3]) # Este vector columna en el libro numpy lo crea así?
print('El determinante de la matriz m_An es:', np.linalg.det(m_An)); print(' ')
# Example A6
print(f"El producto cruz de {m_An} y {m_bn} es:"); print(' '); print(np.outer(m_An, m_bn)); print(' ')


* Usando numpy se crea una matriz A de 3 filas x 3 columnas, de tipo int:
 
[[0 0 0]
 [0 0 0]
 [0 0 0]]
 
* Usando numpy se crea una matriz B de 5 filas x 2 columnas, elemntos de tipo float:
 
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
<class 'numpy.ndarray'>
 
* Usando numpy se crea un arreglo C que inicia en -10 y termina en 5-1, e incrementos de 1:
 
[-5 -4 -3 -2 -1  0  1  2  3  4]
 
* Los arrays son mutables, cambiaremos el elemento en la segunda fila y tercera columna de A por un 2000:
 
[[   0    0    0]
 [   0    0 2000]
 [   0    0    0]]
 
* Ahora convertimos la segunda fila en 2s:
 
[[0 0 0]
 [2 2 2]
 [0 0 0]]
 
* Ejemplo de operación sobre todos los elementos de un array, elevarlos al cubo A:
 
[[0 0 0]
 [8 8 8]
 [0 0 0]]
 
* Operaciones de Matrices
[[1 2 3]
 [1 2 1]
 [0 1 2]] [ 1  6 -2] [ 8  0 -3]
 
El determinante de la matriz m_An es: 13.999999999999996
 
El producto cruz de [[ 5 -2]
 [-3  4]] y [1 3] es:
 
[[ 5 15]
 [-2 -6]
 [-3 -9]
 [ 4 12]]
 
