# Ejercicio 1:
Resolver el ejercicio 3) anterior con la factorización QR del paquete numpy de la matriz A y verificar resultado.

**Nota:** Los siguientes ejercicios están basados en las notas de clase disponibles en (https://github.com/ITAM-DS/Propedeutico/tree/master/Python/clases/2_calculo_DeI) y en el capítulo 6 del libro Numerical Methods in Engineering with Python 3 (Kiusalaas, 2013). Los errores son responsabilidad del autor (SCS).

## Ejercicio 3:
Obtener los factores $P$, $L$, $U$, de la matriz $A$:
$$
A=\left[\begin{array}{ccc}
1 & 4 & 1\\
1 & 6 & -1\\
2 & -1 & 2
\end{array}\right]
$$

y utilizarlos para resolver $Ax = B$ con:
$$
B=\left[\begin{array}{cc}
7 & -1\\
13 & 6\\
5 & 7
\end{array}\right]
$$


# Resolver el sistema con factorización QR
La matriz $A_{m\times n}$ se puede descomponer en dos factores los factores $Q_{m\times n}$ y $R_{m\times n}$. Donde $Q$ es una matriz ortogonal, y $R$ es una matriz triangular superior.
Dado que $AX=B$, entonces $AX=B\Longleftrightarrow QRX=B\Longleftrightarrow RX=Q^{-1}B$. 
Por otro lado, dado que la matriz $Q$ es ortogonal, podemos re-escribir el anterior sistema como $RX=Q^{T}B$.
Así, dado que $R$ es triangular superior, resolvemos el sistema resultante por medio del método de sustitución regresiva. 


# Algoritmo a ejecutar
Para obtener la solución del sistema $Ax=B$ utilizando los factores $Q$, y $R$, se ejecuta el siguiente algoritmo:
1. De la matriz $A$ se obtienen los factores $Q$ y $R$. 
2. Se resuleve el sistema triangular $RX=Q^{T}B$ para obtener $X$.

In [1]:
import scipy
from scipy import linalg
import numpy as np
import pprint

In [2]:
A = np.array([[1.0, 4.0, 1.0],[1.0, 6.0, -1.0], [2.0, -1.0, 2.0]])
B = np.array([[7.0, -1.0], [13.0, 6.0], [5.0, 7.0]])

In [3]:
print('A:')
pprint.pprint(A)
print('B: ')
pprint.pprint(B)

A:
array([[ 1.,  4.,  1.],
       [ 1.,  6., -1.],
       [ 2., -1.,  2.]])
B: 
array([[ 7., -1.],
       [13.,  6.],
       [ 5.,  7.]])


In [4]:
# Paso 1 del algoritmo
Q, R = np.linalg.qr(A)

In [5]:
print('Q:')
pprint.pprint(Q)
print('R:')
pprint.pprint(R)

Q:
array([[-0.40824829, -0.40985242, -0.81569255],
       [-0.40824829, -0.71724173,  0.56471022],
       [-0.81649658,  0.56354707,  0.12549116]])
R:
array([[-2.44948974, -3.26598632, -1.63299316],
       [ 0.        , -6.5064071 ,  1.43448345],
       [ 0.        ,  0.        , -1.12942045]])


In [6]:
# D = Qt*b
D = Q.T@B
print('D:')
pprint.pprint(D)

D:
array([[-12.24744871,  -7.75671752],
       [ -9.37537401,   0.05123155],
       [  2.2588409 ,   5.08239202]])


In [7]:
# Rosolver el sistema:
X = linalg.solve_triangular(R,D)
print('X:')
pprint.pprint(X)

X:
array([[ 5. ,  7.5],
       [ 1. , -1. ],
       [-2. , -4.5]])


In [13]:
print('Verificando resultado AX = B')
print('B:')
pprint.pprint(B)
print('AX:')
pprint.pprint(A@X)

Verificando resultado AX = B
B:
array([[ 7., -1.],
       [13.,  6.],
       [ 5.,  7.]])
AX:
array([[ 7., -1.],
       [13.,  6.],
       [ 5.,  7.]])
