# Ejercicio 2:
Resolver los sistemas de ecuaciones lineales $Ax = b$ con la factorización $P$, $LU$ y verificar resultado.


Nota: Los siguientes ejercicios y notas para su desarrollo están basados en las notas de clase disponibles en (https://github.com/ITAM-DS/Propedeutico/tree/master/Python/clases/2_calculo_DeI) y en el capítulo 6 del libro Numerical Methods in Engineering with Python 3 (Kiusalaas, 2013). Los errores son responsabilidad del autor (SCS).

In [12]:
import scipy
from scipy import linalg
import numpy as np
import pprint

## Parte 1:
$$
A=\left[\begin{array}{ccc}
0 & 1 & -1\\
-2 & 4 & -1\\
-2 & 5 & -4
\end{array}\right],\:b=\left[\begin{array}{c}
3\\
1\\
-2
\end{array}\right]
$$

In [14]:
A = np.array([[0, 1, -1],[-2, 4, -1], [-2,5, -4]])
b = np.array([[3], [1], [-2]])
print('A:')
pprint.pprint(A)
print('b: ')
pprint.pprint(b)

A:
array([[ 0,  1, -1],
       [-2,  4, -1],
       [-2,  5, -4]])
b: 
array([[ 3],
       [ 1],
       [-2]])


In [4]:
# Obtener los factores P, L, U
P, L, U = scipy.linalg.lu(A)
print('P:')
pprint.pprint(P)
print('L:')
pprint.pprint(L)
print('U:')
pprint.pprint(U)
print('Verificando que es igual PA al producto LU')
print('L*U:')
pprint.pprint(L@U)
print('P*A')
pprint.pprint(P@A)

P:
array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])
L:
array([[ 1.,  0.,  0.],
       [-0.,  1.,  0.],
       [ 1.,  1.,  1.]])
U:
array([[-2.,  4., -1.],
       [ 0.,  1., -1.],
       [ 0.,  0., -2.]])
Verificando que es igual PA al producto LU
L*U:
array([[-2.,  4., -1.],
       [ 0.,  1., -1.],
       [-2.,  5., -4.]])
P*A
array([[-2.,  4., -1.],
       [ 0.,  1., -1.],
       [-2.,  5., -4.]])


In [5]:
print('Usando los factores P,L,U para resolver AX = b')
D = scipy.linalg.solve_triangular(L,P@b,lower=True)
x = scipy.linalg.solve_triangular(U,D) 
print('x:')
pprint.pprint(x)

Usando los factores P,L,U para resolver AX = b
x:
array([[10.],
       [ 6.],
       [ 3.]])


In [8]:
print('Verificando resultado Ax = b')
print('B:')
pprint.pprint(b)
print('Ax:')
pprint.pprint(A@x)

Verificando resultado Ax = b
B:
array([[ 3],
       [ 1],
       [-2]])
Ax:
array([[ 3.],
       [ 1.],
       [-2.]])


## Parte 2:
$$
A=\left[\begin{array}{ccc}
0 & 1 & -1\\
-2 & 4 & -1\\
-2 & 5 & -4
\end{array}\right],\:b=\left[\begin{array}{c}
-5\\
7\\
0
\end{array}\right]
$$

In [15]:
A = np.array([[0, 1, -1],[-2, 4, -1], [-2,5, -4]])
b = np.array([[-5], [7], [0]])
print('A:')
pprint.pprint(A)
print('b: ')
pprint.pprint(b)

A:
array([[ 0,  1, -1],
       [-2,  4, -1],
       [-2,  5, -4]])
b: 
array([[-5],
       [ 7],
       [ 0]])


In [16]:
# Obtener los factores P, L, U
P, L, U = scipy.linalg.lu(A)
print('P:')
pprint.pprint(P)
print('L:')
pprint.pprint(L)
print('U:')
pprint.pprint(U)
print('Verificando que es igual PA al producto LU')
print('L*U:')
pprint.pprint(L@U)
print('P*A')
pprint.pprint(P@A)

P:
array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])
L:
array([[ 1.,  0.,  0.],
       [-0.,  1.,  0.],
       [ 1.,  1.,  1.]])
U:
array([[-2.,  4., -1.],
       [ 0.,  1., -1.],
       [ 0.,  0., -2.]])
Verificando que es igual PA al producto LU
L*U:
array([[-2.,  4., -1.],
       [ 0.,  1., -1.],
       [-2.,  5., -4.]])
P*A
array([[-2.,  4., -1.],
       [ 0.,  1., -1.],
       [-2.,  5., -4.]])


In [17]:
print('Usando los factores P,L,U para resolver AX = b')
D = scipy.linalg.solve_triangular(L,P@b,lower=True)
x = scipy.linalg.solve_triangular(U,D) 
print('x:')
pprint.pprint(x)

Usando los factores P,L,U para resolver AX = b
x:
array([[-12.],
       [ -4.],
       [  1.]])


In [18]:
print('Verificando resultado Ax = b')
print('B:')
pprint.pprint(b)
print('Ax:')
pprint.pprint(A@x)

Verificando resultado Ax = b
B:
array([[-5],
       [ 7],
       [ 0]])
Ax:
array([[-5.],
       [ 7.],
       [ 0.]])


## Parte 3:
$$
A=\left[\begin{array}{ccc}
1 & 2 & 2\\
2 & 5 & 7\\
3 & 6 & 6
\end{array}\right],\:b=\left[\begin{array}{c}
0\\
0\\
0
\end{array}\right]
$$


In [19]:
A = np.array([[1, 2, 2],[2, 5, 7], [3, 6, 6]])
b = np.array([[0], [0], [0]])
print('A:')
pprint.pprint(A)
print('b: ')
pprint.pprint(b)

A:
array([[1, 2, 2],
       [2, 5, 7],
       [3, 6, 6]])
b: 
array([[0],
       [0],
       [0]])


In [20]:
# Obtener los factores P, L, U
P, L, U = scipy.linalg.lu(A)
print('P:')
pprint.pprint(P)
print('L:')
pprint.pprint(L)
print('U:')
pprint.pprint(U)
print('Verificando que es igual PA al producto LU')
print('L*U:')
pprint.pprint(L@U)
print('P*A')
pprint.pprint(P@A)

P:
array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])
L:
array([[1.        , 0.        , 0.        ],
       [0.66666667, 1.        , 0.        ],
       [0.33333333, 0.        , 1.        ]])
U:
array([[3., 6., 6.],
       [0., 1., 3.],
       [0., 0., 0.]])
Verificando que es igual PA al producto LU
L*U:
array([[3., 6., 6.],
       [2., 5., 7.],
       [1., 2., 2.]])
P*A
array([[3., 6., 6.],
       [2., 5., 7.],
       [1., 2., 2.]])


La matriz U es singular, por lo que no se peude resolver el sistema con el algoritmo PA = LU.